### ISSUE TITLE
Holodex Next Checklist

### ISSUE THREAD

**Issue by sphinxrave** [HolodexNet/Holodex#706]
Here are the outstanding tasks for MVP and beta deployment:

- [ ] Migrate TLdex Client / Script Editor / Script Manager
- [ ] Implement Multiview functionality
- [x] Implement search functionality
- [ ] Implement multi editing selection tools
    - [ ] Multi topic assignment
    - [ ] Multi mention assignment
    - [ ] Multi source editing
- [ ] Implement intelligent multi editing shortcuts
- [ ] Write the regular edit page/pane for normal users
- [ ] Music tagging
- [ ] TLDex Settings & Replay controls
- [ ] Implement Video page
- [ ] Implement PWA
- [ ] implement Mobile navigations
- [ ] Fix pagination
- [ ] Fix channels page loading
- [ ] Implement playlist sidebar
- [ ] Implement filter settings (homepage)
- [ ] Polish Polish Polish
    - [ ] Search
    - [ ] TopicAutocomplete and VideoAutocomplete needs a progress bar. I think Autocomplete component should add a :loading prop and implement it inside.
- [ ] Implement event driven cache busting to improve performance serverside
- [ ] Add more unit and integration tests (It may be necessary to kitchensink test some components.)

Expanded featureset:
- [ ] PWA notifications for iOS/Android/Windows etc
